





bool start_or_pause
bool stop_and_save
bool closed
float32 speed_limit_kph

string bag_name
string tpk_name
####################################33

int32 rtk_mode
int32 driving_mode # acc or collision avoidance
int32 special_mode  #

####################################33
int32 obs_search_strategy  # 0: donot search obs
int32 speed_mode  #
int32 obs_strategy  #
int32 follow_strategy  #
int32 cross_option  #
int32 reserved_option  #
