(cl:in-package perception_msgs-msg)
(cl:export '(START_OR_PAUSE-VAL
          START_OR_PAUSE
          STOP_AND_SAVE-VAL
          STOP_AND_SAVE
          CLOSED-VAL
          CLOSED
          SPEED_LIMIT_KPH-VAL
          SPEED_LIMIT_KPH
          BAG_NAME-VAL
          BAG_NAME
          TPK_NAME-VAL
          TPK_NAME
          RTK_MODE-VAL
          RTK_MODE
          DRIVING_MODE-VAL
          DRIVING_MODE
          SPECIAL_MODE-VAL
          SPECIAL_MODE
          OBS_SEARCH_STRATEGY-VAL
          OBS_SEARCH_STRATEGY
          SPEED_MODE-VAL
          SPEED_MODE
          OBS_STRATEGY-VAL
          OBS_STRATEGY
          FOLLOW_STRATEGY-VAL
          FOLLOW_STRATEGY
          CROSS_OPTION-VAL
          CROSS_OPTION
          RESERVED_OPTION-VAL
          RESERVED_OPTION
))