(cl:in-package perception_msgs-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          S-VAL
          S
          CUV-VAL
          CUV
          HEADING-VAL
          HEADING
          SPEED-VAL
          SPEED
          SPEEDKMH-VAL
          SPEEDKMH
          RTK_MODE-VAL
          RTK_MODE
          DRIVING_MODE-VAL
          DRIVING_MODE
          SPECIAL_MODE-VAL
          SPECIAL_MODE
          OBS_SEARCH_STRATEGY-VAL
          OBS_SEARCH_STRATEGY
          SPEED_MODE-VAL
          SPEED_MODE
          OBS_STRATEGY-VAL
          OBS_STRATEGY
          FOLLOW_STRATEGY-VAL
          FOLLOW_STRATEGY
          CROSS_OPTION-VAL
          CROSS_OPTION
          RESERVED_OPTION-VAL
          RESERVED_OPTION
          UUID-VAL
          UUID
          LANE_UUID-VAL
          LANE_UUID
          SECTION_UUID-VAL
          SECTION_UUID
))