(cl:in-package gnss_msgs-msg)
(cl:export '(GPS_WEEK-VAL
          GPS_WEEK
          GPS_TIME-VAL
          GPS_TIME
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          V_EAST-VAL
          V_EAST
          V_NORTH-VAL
          V_NORTH
          V_SKY-VAL
          V_SKY
          BASELINE_LEN-VAL
          BASELINE_LEN
          NUM_SAT1-VAL
          NUM_SAT1
          NUM_SAT2-VAL
          NUM_SAT2
          GNSS_STATUS-VAL
          GNSS_STATUS
          GNSS_MODE-VAL
          GNSS_MODE
))