(cl:defpackage perception_msgs-srv
  (:use )
  (:export
   "GLOBALMAP"
   "<GLOBALMAP-REQUEST>"
   "GLOBALMAP-REQUEST"
   "<GLOBALMAP-RESPONSE>"
   "GLOBALMAP-RESPONSE"
   "GLOBALPATH"
   "<GLOBALPATH-REQUEST>"
   "GLOBALPATH-REQUEST"
   "<GLOBALPATH-RESPONSE>"
   "GLOBALPATH-RESPONSE"
   "PTLOCALIZATION"
   "<PTLOCALIZATION-REQUEST>"
   "PTLOCALIZATION-REQUEST"
   "<PTLOCALIZATION-RESPONSE>"
   "PTLOCALIZATION-RESPONSE"
  ))

