// Generated by gencpp from file gnss_msgs/PSAT.msg
// DO NOT EDIT!


#ifndef GNSS_MSGS_MESSAGE_PSAT_H
#define GNSS_MSGS_MESSAGE_PSAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gnss_msgs
{
template <class ContainerAllocator>
struct PSAT_
{
  typedef PSAT_<ContainerAllocator> Type;

  PSAT_()
    : heading(0.0)
    , pitch(0.0)
    , roll(0.0)  {
    }
  PSAT_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , pitch(0.0)
    , roll(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::gnss_msgs::PSAT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_msgs::PSAT_<ContainerAllocator> const> ConstPtr;

}; // struct PSAT_

typedef ::gnss_msgs::PSAT_<std::allocator<void> > PSAT;

typedef boost::shared_ptr< ::gnss_msgs::PSAT > PSATPtr;
typedef boost::shared_ptr< ::gnss_msgs::PSAT const> PSATConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_msgs::PSAT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_msgs::PSAT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gnss_msgs': ['/home/sunhao/prog/wild/src/gnss_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_msgs::PSAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_msgs::PSAT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_msgs::PSAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_msgs::PSAT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_msgs::PSAT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_msgs::PSAT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_msgs::PSAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "122cf7e3b0fb6636d95e8f81f3e2cb17";
  }

  static const char* value(const ::gnss_msgs::PSAT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x122cf7e3b0fb6636ULL;
  static const uint64_t static_value2 = 0xd95e8f81f3e2cb17ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_msgs::PSAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_msgs/PSAT";
  }

  static const char* value(const ::gnss_msgs::PSAT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_msgs::PSAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###\n\
#\n\
#\n\
\n\
float64 heading\n\
float64 pitch\n\
float64 roll\n\
";
  }

  static const char* value(const ::gnss_msgs::PSAT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_msgs::PSAT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.pitch);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PSAT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_msgs::PSAT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_msgs::PSAT_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_MSGS_MESSAGE_PSAT_H
