// Generated by gencpp from file gnss_msgs/UTM.msg
// DO NOT EDIT!


#ifndef GNSS_MSGS_MESSAGE_UTM_H
#define GNSS_MSGS_MESSAGE_UTM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gnss_msgs
{
template <class ContainerAllocator>
struct UTM_
{
  typedef UTM_<ContainerAllocator> Type;

  UTM_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , status(0)  {
    }
  UTM_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , status(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::gnss_msgs::UTM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_msgs::UTM_<ContainerAllocator> const> ConstPtr;

}; // struct UTM_

typedef ::gnss_msgs::UTM_<std::allocator<void> > UTM;

typedef boost::shared_ptr< ::gnss_msgs::UTM > UTMPtr;
typedef boost::shared_ptr< ::gnss_msgs::UTM const> UTMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_msgs::UTM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_msgs::UTM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gnss_msgs': ['/home/sunhao/prog/wild/src/gnss_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_msgs::UTM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_msgs::UTM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_msgs::UTM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_msgs::UTM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_msgs::UTM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_msgs::UTM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_msgs::UTM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da77def20ed3850eb06c17c63aefffaa";
  }

  static const char* value(const ::gnss_msgs::UTM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda77def20ed3850eULL;
  static const uint64_t static_value2 = 0xb06c17c63aefffaaULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_msgs::UTM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_msgs/UTM";
  }

  static const char* value(const ::gnss_msgs::UTM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_msgs::UTM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
#  UTM\n\
\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
int32 status\n\
";
  }

  static const char* value(const ::gnss_msgs::UTM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_msgs::UTM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UTM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_msgs::UTM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_msgs::UTM_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_MSGS_MESSAGE_UTM_H
