// Generated by gencpp from file common_msgs/app.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_APP_H
#define COMMON_MSGS_MESSAGE_APP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs
{
template <class ContainerAllocator>
struct app_
{
  typedef app_<ContainerAllocator> Type;

  app_()
    : stopgo(0)
    , mapnum(0)  {
    }
  app_(const ContainerAllocator& _alloc)
    : stopgo(0)
    , mapnum(0)  {
  (void)_alloc;
    }



   typedef uint8_t _stopgo_type;
  _stopgo_type stopgo;

   typedef uint8_t _mapnum_type;
  _mapnum_type mapnum;





  typedef boost::shared_ptr< ::common_msgs::app_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::app_<ContainerAllocator> const> ConstPtr;

}; // struct app_

typedef ::common_msgs::app_<std::allocator<void> > app;

typedef boost::shared_ptr< ::common_msgs::app > appPtr;
typedef boost::shared_ptr< ::common_msgs::app const> appConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::app_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::app_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/sunhao/wild/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::app_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::app_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::app_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::app_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::app_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::app_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::app_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c51ad9d6e175af3548f31dad6a82baf4";
  }

  static const char* value(const ::common_msgs::app_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc51ad9d6e175af35ULL;
  static const uint64_t static_value2 = 0x48f31dad6a82baf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::app_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/app";
  }

  static const char* value(const ::common_msgs::app_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::app_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 stopgo\n\
uint8 mapnum\n\
";
  }

  static const char* value(const ::common_msgs::app_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::app_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stopgo);
      stream.next(m.mapnum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct app_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::app_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::app_<ContainerAllocator>& v)
  {
    s << indent << "stopgo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stopgo);
    s << indent << "mapnum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mapnum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_APP_H
