// Generated by gencpp from file common_msgs/sensorcameralight.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_SENSORCAMERALIGHT_H
#define COMMON_MSGS_MESSAGE_SENSORCAMERALIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs
{
template <class ContainerAllocator>
struct sensorcameralight_
{
  typedef sensorcameralight_<ContainerAllocator> Type;

  sensorcameralight_()
    : start(0)
    , isvalid(0)
    , timestamp(0)  {
    }
  sensorcameralight_(const ContainerAllocator& _alloc)
    : start(0)
    , isvalid(0)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;

   typedef uint8_t _isvalid_type;
  _isvalid_type isvalid;

   typedef int64_t _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::common_msgs::sensorcameralight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::sensorcameralight_<ContainerAllocator> const> ConstPtr;

}; // struct sensorcameralight_

typedef ::common_msgs::sensorcameralight_<std::allocator<void> > sensorcameralight;

typedef boost::shared_ptr< ::common_msgs::sensorcameralight > sensorcameralightPtr;
typedef boost::shared_ptr< ::common_msgs::sensorcameralight const> sensorcameralightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::sensorcameralight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::sensorcameralight_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/sunhao/wild/src/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::sensorcameralight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::sensorcameralight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::sensorcameralight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::sensorcameralight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::sensorcameralight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::sensorcameralight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::sensorcameralight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d176b03612ab6796db2be50106ee8c1";
  }

  static const char* value(const ::common_msgs::sensorcameralight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d176b03612ab679ULL;
  static const uint64_t static_value2 = 0x6db2be50106ee8c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::sensorcameralight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/sensorcameralight";
  }

  static const char* value(const ::common_msgs::sensorcameralight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::sensorcameralight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 start\n\
uint8 isvalid\n\
int64 timestamp\n\
";
  }

  static const char* value(const ::common_msgs::sensorcameralight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::sensorcameralight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.isvalid);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensorcameralight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::sensorcameralight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::sensorcameralight_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    s << indent << "isvalid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isvalid);
    s << indent << "timestamp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_SENSORCAMERALIGHT_H
