(cl:in-package dnc_msgs-msg)
(cl:export '(SPEICAL-VAL
          SPEICAL
          ENABLE_STEERING-VAL
          ENABLE_STEERING
          ENABLE_BRAKING-VAL
          ENABLE_BRAKING
          ENABLE_DRIVING-VAL
          ENABLE_DRIVING
          ENABLE_ESTOP-VAL
          ENABLE_ESTOP
          ENABLE_GEAR-VAL
          ENABLE_GEAR
          SW_DEG-VAL
          SW_DEG
          SW_RAD-VAL
          SW_RAD
          SPEED_MS-VAL
          SPEED_MS
          SPEED_KMS-VAL
          SPEED_KMS
          AX_MS2-VAL
          AX_MS2
          OMEGA_RAD-VAL
          OMEGA_RAD
          GEAR_MODE-VAL
          GEAR_MODE
          STEERING-VAL
          STEERING
          SPEED-VAL
          SPEED
          REMOTE_FLAG-VAL
          REMOTE_FLAG
))