// Generated by gencpp from file perception_msgs/Localization.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_LOCALIZATION_H
#define PERCEPTION_MSGS_MESSAGE_LOCALIZATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct Localization_
{
  typedef Localization_<ContainerAllocator> Type;

  Localization_()
    : header()
    , state(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , heading(0.0)
    , speed(0.0)
    , utc_time(0.0)  {
    }
  Localization_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , heading(0.0)
    , speed(0.0)
    , utc_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _state_type;
  _state_type state;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _utc_time_type;
  _utc_time_type utc_time;





  typedef boost::shared_ptr< ::perception_msgs::Localization_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::Localization_<ContainerAllocator> const> ConstPtr;

}; // struct Localization_

typedef ::perception_msgs::Localization_<std::allocator<void> > Localization;

typedef boost::shared_ptr< ::perception_msgs::Localization > LocalizationPtr;
typedef boost::shared_ptr< ::perception_msgs::Localization const> LocalizationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::Localization_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::Localization_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'perception_msgs': ['/home/sunhao/prog/wild/src/perception_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::Localization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::Localization_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::Localization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::Localization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::Localization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::Localization_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a17351f38740612c73544203e536dc28";
  }

  static const char* value(const ::perception_msgs::Localization_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa17351f38740612cULL;
  static const uint64_t static_value2 = 0x73544203e536dc28ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/Localization";
  }

  static const char* value(const ::perception_msgs::Localization_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
std_msgs/Header header\n\
\n\
int32 state\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 heading\n\
float64 speed\n\
float64 utc_time\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::Localization_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::Localization_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.heading);
      stream.next(m.speed);
      stream.next(m.utc_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Localization_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::Localization_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::Localization_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "utc_time: ";
    Printer<double>::stream(s, indent + "  ", v.utc_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_LOCALIZATION_H
