// Generated by gencpp from file perception_msgs/Map.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_MAP_H
#define PERCEPTION_MSGS_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <perception_msgs/Section.h>
#include <std_msgs/String.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : header()
    , origin_utm_pt()
    , sections()
    , uuid()
    , id(0)  {
    }
  Map_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , origin_utm_pt(_alloc)
    , sections(_alloc)
    , uuid(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _origin_utm_pt_type;
  _origin_utm_pt_type origin_utm_pt;

   typedef std::vector< ::perception_msgs::Section_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::Section_<ContainerAllocator> >::other >  _sections_type;
  _sections_type sections;

   typedef  ::std_msgs::String_<ContainerAllocator>  _uuid_type;
  _uuid_type uuid;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::perception_msgs::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::perception_msgs::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::perception_msgs::Map > MapPtr;
typedef boost::shared_ptr< ::perception_msgs::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'perception_msgs': ['/home/sunhao/prog/wild/src/perception_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f311c97842ff52d6f2efb99074fbe5db";
  }

  static const char* value(const ::perception_msgs::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf311c97842ff52d6ULL;
  static const uint64_t static_value2 = 0xf2efb99074fbe5dbULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/Map";
  }

  static const char* value(const ::perception_msgs::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
\n\
std_msgs/Header header\n\
\n\
geometry_msgs/Point origin_utm_pt\n\
\n\
perception_msgs/Section[] sections\n\
\n\
std_msgs/String uuid\n\
\n\
int32 id\n\
# -1 : closed map\n\
# 0 : simple map\n\
# 1: topo map\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: perception_msgs/Section\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
\n\
\n\
perception_msgs/Line[] lanes\n\
\n\
int32 direction_mode\n\
\n\
#############################\n\
#int32 id\n\
std_msgs/String uuid\n\
\n\
#############################\n\
\n\
std_msgs/String[] to_section_uuid\n\
std_msgs/String[] from_section_uuid\n\
\n\
\n\
std_msgs/String[] to_lane_uuid\n\
std_msgs/String[] from_lane_uuid\n\
\n\
\n\
std_msgs/String[] to_pt_uuid\n\
std_msgs/String[] from_pt_uuid\n\
\n\
#int32[] to_pt_id\n\
#int32[] from_pt_id\n\
\n\
#############################\n\
\n\
float32 length\n\
float32 highest_speed\n\
float32 traffic_cost\n\
\n\
\n\
\n\
================================================================================\n\
MSG: perception_msgs/Line\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
perception_msgs/Point[] pts\n\
\n\
#############################\n\
int8 is_main # Is the lane center lane of this section\n\
float64 offset\n\
float64 width\n\
\n\
#############################\n\
\n\
#int32 id\n\
std_msgs/String uuid\n\
\n\
#############################\n\
\n\
std_msgs/String main_uuid\n\
\n\
#int32 left_id\n\
std_msgs/String left_uuid\n\
\n\
#int32 right_id\n\
std_msgs/String right_uuid\n\
\n\
\n\
#############################\n\
\n\
#int32 section_id\n\
std_msgs/String section_uuid\n\
\n\
#############################\n\
\n\
\n\
================================================================================\n\
MSG: perception_msgs/Point\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 s\n\
float64 cuv\n\
float64 heading\n\
float64 speed\n\
float64 speedkmh\n\
\n\
############################\n\
\n\
\n\
int32 rtk_mode # 0: 无影响 1： Not rtk stop\n\
int32 driving_mode # acc or collision avoidance\n\
int32 special_mode  #\n\
\n\
####################################33\n\
int32 obs_search_strategy  # 0: donot search obs\n\
int32 speed_mode  #\n\
int32 obs_strategy  #\n\
int32 follow_strategy  #\n\
int32 cross_option  #\n\
int32 reserved_option  #\n\
\n\
\n\
\n\
############################\n\
\n\
#int32 id\n\
std_msgs/String uuid\n\
\n\
#############################\n\
\n\
#int32 line_id\n\
std_msgs/String lane_uuid\n\
\n\
#############################\n\
\n\
#int32 section_id\n\
std_msgs/String section_uuid\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::perception_msgs::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.origin_utm_pt);
      stream.next(m.sections);
      stream.next(m.uuid);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::Map_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "origin_utm_pt: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.origin_utm_pt);
    s << indent << "sections[]" << std::endl;
    for (size_t i = 0; i < v.sections.size(); ++i)
    {
      s << indent << "  sections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::Section_<ContainerAllocator> >::stream(s, indent + "    ", v.sections[i]);
    }
    s << indent << "uuid: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.uuid);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_MAP_H
