// Generated by gencpp from file perception_msgs/V2XData.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_V2XDATA_H
#define PERCEPTION_MSGS_MESSAGE_V2XDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <perception_msgs/V2XUnit.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct V2XData_
{
  typedef V2XData_<ContainerAllocator> Type;

  V2XData_()
    : data()  {
    }
  V2XData_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::perception_msgs::V2XUnit_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception_msgs::V2XUnit_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::perception_msgs::V2XData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::V2XData_<ContainerAllocator> const> ConstPtr;

}; // struct V2XData_

typedef ::perception_msgs::V2XData_<std::allocator<void> > V2XData;

typedef boost::shared_ptr< ::perception_msgs::V2XData > V2XDataPtr;
typedef boost::shared_ptr< ::perception_msgs::V2XData const> V2XDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::V2XData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::V2XData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'perception_msgs': ['/home/sunhao/wild/src/perception_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::V2XData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::V2XData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::V2XData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::V2XData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::V2XData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::V2XData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::V2XData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "784b9cdf681025c07be558fb290fb188";
  }

  static const char* value(const ::perception_msgs::V2XData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x784b9cdf681025c0ULL;
  static const uint64_t static_value2 = 0x7be558fb290fb188ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::V2XData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/V2XData";
  }

  static const char* value(const ::perception_msgs::V2XData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::V2XData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
perception_msgs/V2XUnit[] data\n\
================================================================================\n\
MSG: perception_msgs/V2XUnit\n\
\n\
\n\
\n\
#std_msgs/String info_id\n\
int32  id\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
float32 speed\n\
#float32 ax\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::perception_msgs::V2XData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::V2XData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct V2XData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::V2XData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::V2XData_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::V2XUnit_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_V2XDATA_H
