(cl:in-package common_msgs-msg)
(cl:export '(EPSMETHOD-VAL
          EPSMETHOD
          EPSTORQUE-VAL
          EPSTORQUE
          EPSERROR-VAL
          EPSERROR
          EPSANGLE-VAL
          EPSANGLE
          ESCBRAKEPRESS-VAL
          ESCBRAKEPRESS
          GASPEDAL-VAL
          GASPEDAL
          SYSSTATUS-VAL
          SYSSTATUS
          SPEED-VAL
          SPEED
          LIGHTS-VAL
          LIGHTS
          TURNLIGHT-VAL
          TURNLIGHT
          GEER-VAL
          GEER
          EPB-VAL
          EPB
          ISVALID-VAL
          ISVALID
          TIMESTAMP-VAL
          TIMESTAMP
))