// Generated by gencpp from file dnc_msgs/VizTraj.msg
// DO NOT EDIT!


#ifndef DNC_MSGS_MESSAGE_VIZTRAJ_H
#define DNC_MSGS_MESSAGE_VIZTRAJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dnc_msgs/DNCtrajectory.h>

namespace dnc_msgs
{
template <class ContainerAllocator>
struct VizTraj_
{
  typedef VizTraj_<ContainerAllocator> Type;

  VizTraj_()
    : cluster()  {
    }
  VizTraj_(const ContainerAllocator& _alloc)
    : cluster(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::dnc_msgs::DNCtrajectory_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dnc_msgs::DNCtrajectory_<ContainerAllocator> >::other >  _cluster_type;
  _cluster_type cluster;





  typedef boost::shared_ptr< ::dnc_msgs::VizTraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnc_msgs::VizTraj_<ContainerAllocator> const> ConstPtr;

}; // struct VizTraj_

typedef ::dnc_msgs::VizTraj_<std::allocator<void> > VizTraj;

typedef boost::shared_ptr< ::dnc_msgs::VizTraj > VizTrajPtr;
typedef boost::shared_ptr< ::dnc_msgs::VizTraj const> VizTrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dnc_msgs::VizTraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dnc_msgs::VizTraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dnc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dnc_msgs': ['/home/sunhao/prog/wild/src/dnc_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dnc_msgs::VizTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dnc_msgs::VizTraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnc_msgs::VizTraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnc_msgs::VizTraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnc_msgs::VizTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnc_msgs::VizTraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dnc_msgs::VizTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23126120fd65eed3989e3e640a1add5d";
  }

  static const char* value(const ::dnc_msgs::VizTraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23126120fd65eed3ULL;
  static const uint64_t static_value2 = 0x989e3e640a1add5dULL;
};

template<class ContainerAllocator>
struct DataType< ::dnc_msgs::VizTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dnc_msgs/VizTraj";
  }

  static const char* value(const ::dnc_msgs::VizTraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dnc_msgs::VizTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dnc_msgs/DNCtrajectory[] cluster\n\
================================================================================\n\
MSG: dnc_msgs/DNCtrajectory\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
std_msgs/Header header\n\
\n\
int32 mode\n\
float32 desired_ax\n\
dnc_msgs/DNCpath path\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: dnc_msgs/DNCpath\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
\n\
dnc_msgs/DNCpoint[] pts\n\
bool s_flag\n\
bool h_flag\n\
================================================================================\n\
MSG: dnc_msgs/DNCpoint\n\
#############################\n\
###       SunHao          ###\n\
#############################\n\
\n\
\n\
float64 x\n\
float64 y\n\
float64 s\n\
\n\
float64 cuv\n\
float64 heading\n\
float64 speed\n\
\n\
float32 h\n\
";
  }

  static const char* value(const ::dnc_msgs::VizTraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dnc_msgs::VizTraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cluster);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VizTraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnc_msgs::VizTraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dnc_msgs::VizTraj_<ContainerAllocator>& v)
  {
    s << indent << "cluster[]" << std::endl;
    for (size_t i = 0; i < v.cluster.size(); ++i)
    {
      s << indent << "  cluster[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dnc_msgs::DNCtrajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.cluster[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNC_MSGS_MESSAGE_VIZTRAJ_H
