# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from little_ant_msgs/State1.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class State1(genpy.Message):
  _md5sum = "d700876b21c15951961ee3bec1bee8b6"
  _type = "little_ant_msgs/State1"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """#VCU_8 0x151

std_msgs/Header header

uint8 GEAR_DRIVE   = 11
uint8 GEAR_NEUTRAL = 12
uint8 GEAR_REVERSE = 13

uint8 act_gear
float32 accel_pedal_position
uint8 brake_pedal
bool accel_pedal_position_valid
bool act_gear_valid
bool brake_pedal_valid
bool vehicle_ready
bool driverless_mode



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  GEAR_DRIVE = 11
  GEAR_NEUTRAL = 12
  GEAR_REVERSE = 13

  __slots__ = ['header','act_gear','accel_pedal_position','brake_pedal','accel_pedal_position_valid','act_gear_valid','brake_pedal_valid','vehicle_ready','driverless_mode']
  _slot_types = ['std_msgs/Header','uint8','float32','uint8','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,act_gear,accel_pedal_position,brake_pedal,accel_pedal_position_valid,act_gear_valid,brake_pedal_valid,vehicle_ready,driverless_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(State1, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.act_gear is None:
        self.act_gear = 0
      if self.accel_pedal_position is None:
        self.accel_pedal_position = 0.
      if self.brake_pedal is None:
        self.brake_pedal = 0
      if self.accel_pedal_position_valid is None:
        self.accel_pedal_position_valid = False
      if self.act_gear_valid is None:
        self.act_gear_valid = False
      if self.brake_pedal_valid is None:
        self.brake_pedal_valid = False
      if self.vehicle_ready is None:
        self.vehicle_ready = False
      if self.driverless_mode is None:
        self.driverless_mode = False
    else:
      self.header = std_msgs.msg.Header()
      self.act_gear = 0
      self.accel_pedal_position = 0.
      self.brake_pedal = 0
      self.accel_pedal_position_valid = False
      self.act_gear_valid = False
      self.brake_pedal_valid = False
      self.vehicle_ready = False
      self.driverless_mode = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bf6B().pack(_x.act_gear, _x.accel_pedal_position, _x.brake_pedal, _x.accel_pedal_position_valid, _x.act_gear_valid, _x.brake_pedal_valid, _x.vehicle_ready, _x.driverless_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.act_gear, _x.accel_pedal_position, _x.brake_pedal, _x.accel_pedal_position_valid, _x.act_gear_valid, _x.brake_pedal_valid, _x.vehicle_ready, _x.driverless_mode,) = _get_struct_Bf6B().unpack(str[start:end])
      self.accel_pedal_position_valid = bool(self.accel_pedal_position_valid)
      self.act_gear_valid = bool(self.act_gear_valid)
      self.brake_pedal_valid = bool(self.brake_pedal_valid)
      self.vehicle_ready = bool(self.vehicle_ready)
      self.driverless_mode = bool(self.driverless_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bf6B().pack(_x.act_gear, _x.accel_pedal_position, _x.brake_pedal, _x.accel_pedal_position_valid, _x.act_gear_valid, _x.brake_pedal_valid, _x.vehicle_ready, _x.driverless_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.act_gear, _x.accel_pedal_position, _x.brake_pedal, _x.accel_pedal_position_valid, _x.act_gear_valid, _x.brake_pedal_valid, _x.vehicle_ready, _x.driverless_mode,) = _get_struct_Bf6B().unpack(str[start:end])
      self.accel_pedal_position_valid = bool(self.accel_pedal_position_valid)
      self.act_gear_valid = bool(self.act_gear_valid)
      self.brake_pedal_valid = bool(self.brake_pedal_valid)
      self.vehicle_ready = bool(self.vehicle_ready)
      self.driverless_mode = bool(self.driverless_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bf6B = None
def _get_struct_Bf6B():
    global _struct_Bf6B
    if _struct_Bf6B is None:
        _struct_Bf6B = struct.Struct("<Bf6B")
    return _struct_Bf6B
