# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dnc_msgs/VehStat.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehStat(genpy.Message):
  _md5sum = "e80772b9bb70a4ec8d045b4f390e4eb8"
  _type = "dnc_msgs/VehStat"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """

float32 vx
float32 v_kmh
float32 sw_deg
float32 sw_rad

int32 gear_status
"""
  __slots__ = ['vx','v_kmh','sw_deg','sw_rad','gear_status']
  _slot_types = ['float32','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vx,v_kmh,sw_deg,sw_rad,gear_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehStat, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vx is None:
        self.vx = 0.
      if self.v_kmh is None:
        self.v_kmh = 0.
      if self.sw_deg is None:
        self.sw_deg = 0.
      if self.sw_rad is None:
        self.sw_rad = 0.
      if self.gear_status is None:
        self.gear_status = 0
    else:
      self.vx = 0.
      self.v_kmh = 0.
      self.sw_deg = 0.
      self.sw_rad = 0.
      self.gear_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fi().pack(_x.vx, _x.v_kmh, _x.sw_deg, _x.sw_rad, _x.gear_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.vx, _x.v_kmh, _x.sw_deg, _x.sw_rad, _x.gear_status,) = _get_struct_4fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fi().pack(_x.vx, _x.v_kmh, _x.sw_deg, _x.sw_rad, _x.gear_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.vx, _x.v_kmh, _x.sw_deg, _x.sw_rad, _x.gear_status,) = _get_struct_4fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fi = None
def _get_struct_4fi():
    global _struct_4fi
    if _struct_4fi is None:
        _struct_4fi = struct.Struct("<4fi")
    return _struct_4fi
