# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from perception_msgs/Point.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Point(genpy.Message):
  _md5sum = "bccfec239a88b4161680fb692e3d84e6"
  _type = "perception_msgs/Point"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#############################
###       SunHao          ###
#############################

float64 x
float64 y
float64 z
float64 s
float64 cuv
float64 heading
float64 speed
float64 speedkmh

############################


int32 rtk_mode # 0: 无影响 1： Not rtk stop
int32 driving_mode # acc or collision avoidance
int32 special_mode  #

####################################33
int32 obs_search_strategy  # 0: donot search obs
int32 speed_mode  #
int32 obs_strategy  #
int32 follow_strategy  #
int32 cross_option  #
int32 reserved_option  #



############################

#int32 id
std_msgs/String uuid

#############################

#int32 line_id
std_msgs/String lane_uuid

#############################

#int32 section_id
std_msgs/String section_uuid



================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['x','y','z','s','cuv','heading','speed','speedkmh','rtk_mode','driving_mode','special_mode','obs_search_strategy','speed_mode','obs_strategy','follow_strategy','cross_option','reserved_option','uuid','lane_uuid','section_uuid']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','int32','int32','int32','int32','int32','int32','int32','int32','int32','std_msgs/String','std_msgs/String','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,s,cuv,heading,speed,speedkmh,rtk_mode,driving_mode,special_mode,obs_search_strategy,speed_mode,obs_strategy,follow_strategy,cross_option,reserved_option,uuid,lane_uuid,section_uuid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Point, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.s is None:
        self.s = 0.
      if self.cuv is None:
        self.cuv = 0.
      if self.heading is None:
        self.heading = 0.
      if self.speed is None:
        self.speed = 0.
      if self.speedkmh is None:
        self.speedkmh = 0.
      if self.rtk_mode is None:
        self.rtk_mode = 0
      if self.driving_mode is None:
        self.driving_mode = 0
      if self.special_mode is None:
        self.special_mode = 0
      if self.obs_search_strategy is None:
        self.obs_search_strategy = 0
      if self.speed_mode is None:
        self.speed_mode = 0
      if self.obs_strategy is None:
        self.obs_strategy = 0
      if self.follow_strategy is None:
        self.follow_strategy = 0
      if self.cross_option is None:
        self.cross_option = 0
      if self.reserved_option is None:
        self.reserved_option = 0
      if self.uuid is None:
        self.uuid = std_msgs.msg.String()
      if self.lane_uuid is None:
        self.lane_uuid = std_msgs.msg.String()
      if self.section_uuid is None:
        self.section_uuid = std_msgs.msg.String()
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.s = 0.
      self.cuv = 0.
      self.heading = 0.
      self.speed = 0.
      self.speedkmh = 0.
      self.rtk_mode = 0
      self.driving_mode = 0
      self.special_mode = 0
      self.obs_search_strategy = 0
      self.speed_mode = 0
      self.obs_strategy = 0
      self.follow_strategy = 0
      self.cross_option = 0
      self.reserved_option = 0
      self.uuid = std_msgs.msg.String()
      self.lane_uuid = std_msgs.msg.String()
      self.section_uuid = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d9i().pack(_x.x, _x.y, _x.z, _x.s, _x.cuv, _x.heading, _x.speed, _x.speedkmh, _x.rtk_mode, _x.driving_mode, _x.special_mode, _x.obs_search_strategy, _x.speed_mode, _x.obs_strategy, _x.follow_strategy, _x.cross_option, _x.reserved_option))
      _x = self.uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.lane_uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.section_uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.uuid is None:
        self.uuid = std_msgs.msg.String()
      if self.lane_uuid is None:
        self.lane_uuid = std_msgs.msg.String()
      if self.section_uuid is None:
        self.section_uuid = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 100
      (_x.x, _x.y, _x.z, _x.s, _x.cuv, _x.heading, _x.speed, _x.speedkmh, _x.rtk_mode, _x.driving_mode, _x.special_mode, _x.obs_search_strategy, _x.speed_mode, _x.obs_strategy, _x.follow_strategy, _x.cross_option, _x.reserved_option,) = _get_struct_8d9i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.uuid.data = str[start:end].decode('utf-8')
      else:
        self.uuid.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lane_uuid.data = str[start:end].decode('utf-8')
      else:
        self.lane_uuid.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.section_uuid.data = str[start:end].decode('utf-8')
      else:
        self.section_uuid.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d9i().pack(_x.x, _x.y, _x.z, _x.s, _x.cuv, _x.heading, _x.speed, _x.speedkmh, _x.rtk_mode, _x.driving_mode, _x.special_mode, _x.obs_search_strategy, _x.speed_mode, _x.obs_strategy, _x.follow_strategy, _x.cross_option, _x.reserved_option))
      _x = self.uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.lane_uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.section_uuid.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.uuid is None:
        self.uuid = std_msgs.msg.String()
      if self.lane_uuid is None:
        self.lane_uuid = std_msgs.msg.String()
      if self.section_uuid is None:
        self.section_uuid = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 100
      (_x.x, _x.y, _x.z, _x.s, _x.cuv, _x.heading, _x.speed, _x.speedkmh, _x.rtk_mode, _x.driving_mode, _x.special_mode, _x.obs_search_strategy, _x.speed_mode, _x.obs_strategy, _x.follow_strategy, _x.cross_option, _x.reserved_option,) = _get_struct_8d9i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.uuid.data = str[start:end].decode('utf-8')
      else:
        self.uuid.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lane_uuid.data = str[start:end].decode('utf-8')
      else:
        self.lane_uuid.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.section_uuid.data = str[start:end].decode('utf-8')
      else:
        self.section_uuid.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d9i = None
def _get_struct_8d9i():
    global _struct_8d9i
    if _struct_8d9i is None:
        _struct_8d9i = struct.Struct("<8d9i")
    return _struct_8d9i
