(cl:defpackage common_msgs-srv
  (:use )
  (:export
   "TRANSLATECOORDINATE"
   "<TRANSLATECOORDINATE-REQUEST>"
   "TRANSLATECOORDINATE-REQUEST"
   "<TRANSLATECOORDINATE-RESPONSE>"
   "TRANSLATECOORDINATE-RESPONSE"
  ))

